name: devshell
on:
  workflow_dispatch:
    inputs:
      symbol:
        required: true
        default: "BTC"
        type: choice
        options:
        - BTC
        - ETH
      short_25:
        required: true
        type: number
      short_50:
        required: true
        type: number
      short_100:
        required: true
        type: number
      long_100:
        required: true
        type: number
      long_50:
        required: true
        type: number
      long_25:
        required: true
        type: number

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "tstachl/seed_tstachl_tbdliquidation"
          TMP_REPO: "/tmp/repo"
          SYM_INFO: "/symbol_info/seed_tstachl_tbdliquidation.json"
        run: |
          source "$(nix-build shell.nix)/env.bash"

          CDATE=$(TZ=UTC date +%Y%m%dT)
          CTIME=$(TZ=UTC date +%H:%M)

          clone $REPO $TMP_REPO
          add ${{ inputs.symbol }} ${CDATE} ${CTIME} ${{ inputs.short_25 }} ${{ inputs.short_50 }} ${{ inputs.short_100 }} ${{ inputs.long_100 }} ${{ inputs.long_50 }} ${{ inputs.long_25 }}
          commit $TMP_REPO $CDATE $CTIME

